(ns datomic-simple.util)

(defn map-keys
  "Given a map and fn that takes a key, creates a new map with keys generated by the fn."
  [oldmap kfn]
  (->> oldmap
    (map (fn [[key val]]
           [(kfn key) val]))
    (into {})))

(defn namespace-keys
  "Given a namespace and map, namespaces the keys of the map."
  [nsp attr]
  (map-keys attr #(keyword (name nsp) (name %))))

(defn localize-attr
  "Creates a map with original keyword keys stripped of their namespace i.e. :url/name -> :name."
  [attr]
  (map-keys attr #(keyword (name %))))
