(ns datomic-simple.util)

(defn map-keys
  "Given a map and fn that takes a key, creates a new map with keys generated by the fn."
  [oldmap kfn]
  (->> oldmap
    (map (fn [[key val]] [(kfn key) val])) flatten (apply hash-map)))

(defn namespace-keys
  "Given a namespace and map, namespaces the keys of the map."
  [nsp attr]
  (map-keys attr #(keyword (name nsp) (name %))))
